# Generated by Django 5.2.8 on 2026-02-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_parkingsession_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='grace_period_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
