# Generated by Django 5.2.7 on 2025-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('controller', 'Controller'), ('manager', 'Manager'), ('superuser', 'Superuser')], default='user', max_length=20),
        ),
    ]
