# Generated by Django 5.2.7 on 2026-02-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start_time'], 'verbose_name': 'Controller Shift', 'verbose_name_plural': 'Controller Shifts'},
        ),
    ]
