# Generated by Django 5.2.8 on 2026-02-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_shift_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_violations',
            field=models.IntegerField(default=0),
        ),
    ]
