# Generated by Django 5.2.8 on 2026-02-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_max_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='violations_count',
            field=models.IntegerField(default=0),
        ),
    ]
