# Generated by Django 5.2.7 on 2026-02-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(default='Italy', max_length=100)),
                ('center_latitude', models.FloatField(blank=True, null=True)),
                ('center_longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=2.5, max_digits=6)),
                ('tariff_config_json', models.TextField(default='{\n    "type": "HOURLY_LINEAR",\n    "daily_rate": 20.00,\n    "day_base_rate": 2.50,\n    "night_base_rate": 1.50,\n    "night_start_time": "22:00",\n    "night_end_time": "06:00",\n    "flex_rules": []\n}')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('polygon_coordinates', models.TextField(default='[]', help_text='JSON array of coordinates forming the parking polygon')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='parkings.parking')),
            ],
            options={
                'verbose_name': 'Parking Entrance',
                'verbose_name_plural': 'Parking Entrances',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('floor', models.CharField(blank=True, default='0', max_length=10)),
                ('zone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parkings.parking')),
            ],
        ),
    ]
