# Generated by Django 5.2.7 on 2026-02-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        # Questo comando SQL viene eseguito direttamente sul database
        migrations.RunSQL(
            "ALTER TABLE parkings_parking DROP COLUMN IF EXISTS grace_period_minutes;"
        ),
    ]
